### ISSUE TITLE
Could not setup repo: Error: Request failed with status code 500 (Gitea)

### ISSUE THREAD

**Issue by vsile** [metroline/metroline#16] opened 2020-12-21 12:20 UTC
I try to setup my repo. I click "Setup" button and get the next error:
![изображение](https://user-images.githubusercontent.com/9244347/102775355-bf19d600-439d-11eb-9742-8dee1b7f9eda.png)

Logs from docker-compose (server):
```
server_1    | 84dd83eac9d8 1 2020-12-21T11:34:12.538Z error  metroline.server:handleError Error: Request failed with status code 422
server_1    |     at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
server_1    |     at settle (/app/node_modules/axios/lib/core/settle.js:17:12)
server_1    |     at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:236:11)
server_1    |     at IncomingMessage.emit (events.js:326:22)
server_1    |     at endReadableNT (_stream_readable.js:1223:12)
server_1    |     at processTicksAndRejections (internal/process/task_queues.js:84:21)
server_1    | Error: Thrown at:
server_1    |     at data (/app/src/commons/axios/ensure-stack-trace.ts:6:36)
server_1    |     at t.Gitea.webhook [as addDeployKey] (/app/src/server/git-servers/gitea/gitea.ts:234:13)
server_1    |     at async Promise.all (index 0)
server_1    |     at t.setupRepoRoute (/app/src/server/repos/setup-repo.ts:29:21) 
server_1    | POST /api/v1/repos/5fdcc4016fa5b7b35d49784a/setup 500 120 - 1142.998 ms
```
OAuth and getting repository list work fine. 
Gitea 1.13.0
Gitea API 1.1.1
images: metroline/ui:latest, metroline/server:latest, metroline/runner:latest, mongo:4.2-bionic

How to fix it?

**Comment by vsile** [comment] 2020-12-22 10:57
Additional info:
We use the next environments:
```
ui:
    ports:
        - "3000:80"
    environment:
        METROLINE_SERVER_URL: https://my.domain.org:9443/server # mapping with proxy to http://10.250.24.40:3001

server:
    ports:
        - "3001:80"
    environment:
        METROLINE_HOST: https://my.domain.org:9443/server # mapping with proxy to http://10.250.24.40:3001
        METROLINE_UI_URL: https://my.domain.org:9443 # mapping with proxy to http://10.250.24.40:3000
```

**Comment by gempain** [comment] 2020-12-22 11:08
@vsile I think you're having this issue because the deploy key may already exist. Can you try removing all webhooks and keys in your Gitea project please ?

**Comment by vsile** [comment] 2020-12-22 12:47
There are no deploy keys in Gitea Repository.
![изображение](https://user-images.githubusercontent.com/9244347/102889793-55b4c880-446c-11eb-817c-70eeb185c263.png)

Also I removed all webhooks:
![изображение](https://user-images.githubusercontent.com/9244347/102889976-ae846100-446c-11eb-966a-f1f1e23d16d2.png)

No effect. I get the same error: `Could not setup repo: Error: Request failed with status code 500`.

**Comment by vsile** [comment] 2020-12-22 13:10
![изображение](https://user-images.githubusercontent.com/9244347/102890407-74678f00-446d-11eb-8f33-4016baa52797.png)

Why does the url at the picture above not include the /server/ path according to my environment?
The url should probably be
```
https://ci.gnivc.ru:9443/server/socket.io/?EIO=3&transport=polling&t=NQAT1Al
```

**Comment by gempain** [comment] 2020-12-22 15:33
So, basically, the server exposes routes `/auth`, `/api` and `/socket.io`. Your reverse proxy should point `/socket.io`, `/api/*` and `/auth/*` to Metroline server. This will fix the first issue. You might have to strip the path prefix.

I realize however that there is a bug in the way we initialize the socket.io client... it doesn't pick up the subpath `/server` properly.

I'll try to find some time to release a fix for this. Until then, you'll have to keep your server under `/` and configure your proxy as I mentioned above. That's how we deploy the demo and it works like a charm.

Once that's resolve, we might be able to find the cause of your Gitea issues. But right now I don't see what would be wrong. Are you the owner of the repos ? That's all I could see really, you have to be an admin/owner to setup the repos.

**Comment by vsile** [comment] 2020-12-22 17:11
I have added a new location `socket.io` to Nginx config.
```
location / {
	proxy_pass http://10.250.24.40:3000/;
	proxy_set_header Host $host;
	proxy_set_header X-Real_IP $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header X-Forwarded-Proto $scheme;
}

location /server/ {
	proxy_pass http://10.250.24.40:3001/;
	proxy_set_header Host $host;
	proxy_set_header X-Real_IP $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header X-Forwarded-Proto $scheme;
}

location /socket.io/ {
	proxy_pass http://10.250.24.40:3001/socket.io/;
	proxy_set_header Host $host;
	proxy_set_header Upgrade $http_upgrade;
	proxy_set_header Connection "upgrade";
	proxy_set_header X-Real_IP $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header X-Forwarded-Proto $scheme;
}
```
It fixed the socket error.

But the Issue error `{"statusCode":500,"path":"/api/v1/repos/5fdcc4016fa5b7b35d49784a/setup","message":"Request failed with status code 422"}` still occurs

**Comment by gempain** [comment] 2020-12-22 22:22
Good, we're making progress :) Can you enabled debug by setting `DEBUG=metroline*` and give me the logs ? I'm trying to figure out why Gitea won't let you configure the repo. There might be an issue with the API response validation.

**Comment by vsile** [comment] 2020-12-22 22:49
I've found the solution.
In our Gitea config (conf/app.ini) we had disabled ssh setting.
So I changed
```
[server]
DISABLE_SSH = true
```
to
```
[server]
DISABLE_SSH = false
```
The error is resolved. Thank you!

**Comment by gempain** [comment] 2020-12-23 09:52
@vsile happy to help 😄  I'm not sure why this was causing the issue, as we don't use SSH when setting up the repo. I'm closing, but feel free to give more info on this as I'd like to understand what happened. Can you provide error logs so I see what you were getting ?

**Closed by gempain** 2020-12-23 09:52 UTC

**Comment by vsile** [comment] 2020-12-23 10:25
I turned on DEBUG mode and reset DISABLE_SSH=true (temporary). 
On click the Setup button I get the next log:
```
server_1    | 2020-12-23T10:07:24.310Z metroline.server:handleError Error: Request failed with status code 422
server_1    |     at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
server_1    |     at settle (/app/node_modules/axios/lib/core/settle.js:17:12)
server_1    |     at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:236:11)
server_1    |     at IncomingMessage.emit (events.js:326:22)
server_1    |     at endReadableNT (_stream_readable.js:1223:12)
server_1    |     at processTicksAndRejections (internal/process/task_queues.js:84:21)
server_1    | Error: Thrown at:
server_1    |     at data (/app/src/commons/axios/ensure-stack-trace.ts:6:36)
server_1    |     at t.Gitea.webhook [as addDeployKey] (/app/src/server/git-servers/gitea/gitea.ts:234:13)
server_1    |     at async Promise.all (index 0)
server_1    |     at t.setupRepoRoute (/app/src/server/repos/setup-repo.ts:29:21)
server_1    | 2020-12-23T10:07:24.310Z metroline.server:handleError {
server_1    |   "message": "Request failed with status code 422",
server_1    |   "name": "Error",
server_1    |   "stack": "Error: Request failed with status code 422\n    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/app/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:236:11)\n    at IncomingMessage.emit (events.js:326:22)\n    at endReadableNT (_stream_readable.js:1223:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)\nError: Thrown at:\n    at data (/app/src/commons/axios/ensure-stack-trace.ts:6:36)\n    at t.Gitea.webhook [as addDeployKey] (/app/src/server/git-servers/gitea/gitea.ts:234:13)\n    at async Promise.all (index 0)\n    at t.setupRepoRoute (/app/src/server/repos/setup-repo.ts:29:21)",
server_1    |   "config": {
server_1    |     "url": "/api/v1/repos/gitea/test-repo-4/keys",
server_1    |     "method": "post",
server_1    |     "data": "{\"key\":\"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDBqxklaYw1feC0uagSc90YJb3vm91X1SH7CK96ulWy5EHntpZlpiFpvaSQtbXgJ/wtozPuGbV8KxgdjW3fKG5uwhtkFfyrkxPIT5kAtKNuIax+5pnYjjLPabCad2dKdTUZDaks67DkdF7kVHVCnD/tss8Fjh//XnLyFrG0oEaF+n4w+n81MVeacYM/HKwac9AzRES/CGTeyKSGI3p1VzgMcAqt+BLyHpww4rtLmjhoRDS/c7j9Vs9KiVZpkw+aBpJ6W5hwqEYuw1HaMQMfbJhJKY974YRJDpxMJUGDdKx7wFWhfHfKeOOg5eqEFvj7dVum42NH6aCdtbzlktRNoJJ+IN0b1n0hdt0Ijim4kARd9ujp5m1/a4/fqoCsuTE5S3Xli+A90o47ACztHfiitgDzaIrWJrv6iaq+AfSBFaPrc9RT6+rRx87F0r59KRUMM0lklJt5HQ2s1r/8nuSAImDJCO4UdZnezOeOtkGitvB/3xYrAKz5aTO11tQGOBbv/plY4tqJ+tRf7ArX05XXsUZSp8o+rytUcZEtfgzo+r7KvJBuS4BnZUBtLIwhZkznPT55rTD59uxbJSXfTslQL09P19fX6WWbMrp3HAqkCcFdof1CdPZw73aLUpIAxHyqsjHOXFtFitdsuYYqs4AY4uh+5hRYAo9mFIUieQLyEKeUjw== (unnamed)\",\"title\":\"metroline deploy key\",\"read_only\":true}",
server_1    |     "headers": {
server_1    |       "Accept": "application/json, text/plain, */*",
server_1    |       "Content-Type": "application/json;charset=utf-8",
server_1    |       "Authorization": "bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJnbnQiOjIsInR0IjowLCJleHAiOjE2MDg3MjE0MjgsImlhdCI6MTYwODcxNzgyOH0.q5rfk7B5eorDJvvVXSrqer9dDYDDDQpRNdQl2VGA1intH44LmT4uUQKJB_b2HJluKQ-UYFUIYo5Vd5l7N7Q_-A",
server_1    |       "User-Agent": "axios/0.19.2",
server_1    |       "Content-Length": 792
server_1    |     },
server_1    |     "baseURL": "http://10.250.24.52:3333",
server_1    |     "transformRequest": [
server_1    |       null
server_1    |     ],
server_1    |     "transformResponse": [
server_1    |       null
server_1    |     ],
server_1    |     "timeout": 0,
server_1    |     "xsrfCookieName": "XSRF-TOKEN",
server_1    |     "xsrfHeaderName": "X-XSRF-TOKEN",
server_1    |     "maxContentLength": -1,
server_1    |     "errorContext": {}
server_1    |   }
server_1    | }
server_1    | 2020-12-23T10:07:24.310Z metroline.server:handleError response {
server_1    |   "message": "SSH is disabled",
server_1    |   "url": "http://10.250.24.52:3333/api/swagger"
server_1    | }
server_1    | e37ad50a581c 1 2020-12-23T10:07:24.310Z error  metroline.server:handleError Error: Request failed with status code 422
server_1    |     at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
server_1    |     at settle (/app/node_modules/axios/lib/core/settle.js:17:12)
server_1    |     at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:236:11)
server_1    |     at IncomingMessage.emit (events.js:326:22)
server_1    |     at endReadableNT (_stream_readable.js:1223:12)
server_1    |     at processTicksAndRejections (internal/process/task_queues.js:84:21)
server_1    | Error: Thrown at:
server_1    |     at data (/app/src/commons/axios/ensure-stack-trace.ts:6:36)
server_1    |     at t.Gitea.webhook [as addDeployKey] (/app/src/server/git-servers/gitea/gitea.ts:234:13)
server_1    |     at async Promise.all (index 0)
server_1    |     at t.setupRepoRoute (/app/src/server/repos/setup-repo.ts:29:21) 
server_1    | 2020-12-23T10:07:24.311Z metroline.server:handleError {
server_1    |   statusCode: 500,
server_1    |   path: '/api/v1/repos/5fe31604a346645d6f7ffbb0/setup',
server_1    |   message: 'Request failed with status code 422',
server_1    |   error: undefined
server_1    | }
server_1    | POST /api/v1/repos/5fe31604a346645d6f7ffbb0/setup 500 120 - 2127.936 ms

```

**Comment by gempain** [comment] 2020-12-23 10:55
Okay, found it 😄  It makes sense ! Since SSH is disabled, you can't add an SSH key to your repository... thanks for sharing !
